fix: flake on TestSSHAuthSockPathHandling test (#8574)
When testing the TestSSHAuthSockPathHandling, Alex encountered
rightfully a flake on this test, leading to this error:

```
Error: module at source dir "" doesn't exist or is invalid
```

It turns out that the error comes from the tests being run in parallel
whilst relying on the same client

Signed-off-by: Guillaume de Rouville <guillaume@dagger.com>
Co-authored-by: Guillaume de Rouville <guillaume@dagger.com>